version: '3.8'

services:
  weather-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    networks:
      - weather_network

networks:
  weather_network:
    driver: bridge
